name: Compile examples
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        fqbn:
          - arduino:avr:uno

    steps:
      - uses: actions/checkout@v3
      - uses: arduino/compile-sketches@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fqbn: ${{ matrix.fqbn }}
          sketch-paths: |
            - examples/hello_Astronode
            - examples/hk_logger_sd
          libraries: |
            - source-path: ./
            - source-url: https://github.com/adafruit/Adafruit_SleepyDog.git
            - name: SD
            - name: SPI
